<base href="" />

<title>
    <?= $title ?? 'Hackathon Autumn 2023' ?>
</title>

<meta charset="utf-8">

<!-- SEO Meta -->
<meta name="language" content="RU" />
<meta name="robots" content="noindex,nofollow" />
<meta name="title" content="<?= $title ?? 'Hackathon Autumn 2023' ?>" />
<meta name="description"
    content="<?= $description ?? 'Оджетто — Быстро выводим на рынок новые продукты на готовых платформах, развиваем custom build решения в парадигме микросервисов. IT-консалтинг, разработка, дизайн, поддержка, веб-аналитика.' ?>" />
<meta name="keywords" content="<?= $title ?? '' ?>" />
<meta name="viewport" content="width=device-width, initial-scale=1" />

<!-- Apple Meta Tags -->
<meta name="apple-mobile-web-app-capable" content="yes" />
<meta name="apple-touch-fullscreen" content="yes" />
<meta name="apple-mobile-web-app-status-bar-style" content="black" />
<meta name="format-detection" content="telephone=no" />

<!-- About Creator App -->
<meta name="owner" content="nona@localzet.com" />
<meta name="designer" content="nona@localzet.com" />
<meta name="author" content="NONA Team" />
<meta name="copyright" content="NONA Team" />
<meta name="reply-to" content="nona@localzet.com" />

<!-- System Information -->
<meta name="generator" content="Triangle Framework" />

<!-- HTTP Equiv -->
<meta http-equiv="Expires" content="60" />
<meta http-equiv="Pragma" content="no-cache" />
<meta http-equiv="Cache-Control" content="no-cache" />
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<meta http-equiv="X-UA-Compatible" content="IE=edge" />

<!-- SEO Link -->
<link rel="canonical" href="https://hackathon.localzet.com/">
<link rel="icon" type="image/png" href="https://oggetto.ru/favicon.png">
<link rel="shortcut icon" type="image/png" href="https://oggetto.ru/favicon.png">

<!-- Fonts -->
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Inter:300,400,500,600,700" />
<link rel="stylesheet"
    href="https://fonts.googleapis.com/css2?family=Montserrat:wght@300;400;600;700;900&amp;display=swap">

<!-- Styles -->
<link rel="stylesheet" type="text/css" href="/assets/plugins/custom/fullcalendar/fullcalendar.bundle.css" />
<link rel="stylesheet" type="text/css" href="/assets/plugins/custom/datatables/datatables.bundle.css" />
<link rel="stylesheet" type="text/css" href="/assets/plugins/global/plugins.bundle.css" />
<link rel="stylesheet" type="text/css" href="/assets/css/style.bundle.css" />